.github/workflows/update-swagger.yml
=> fix swagger builder

.github/workflows/update-swagger.yml
=> add doc regen

.github/workflows/update-swagger.yml
=> fix doc build

.github/workflows/update-swagger.yml
=> downgrade swagger version

.github/workflows/update-swagger.yml
=> fix swagger version

License, docs/api.md, docs/docs.go, docs/swagger.md, docs/swagger.yaml, main.go
- add license file
- change license to follow standard
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
=> cleanup demo code

.github/workflows/ci.yml, api/argo-templates/render.go, api/argo-templates/render_test.go, api/controllers/v1/ncn.go, api/controllers/v1/ncn_test.go, api/controllers/v2/ncn_test.go, api/mocks/services/workflow.go, api/models/ncn_rebuild.go, api/services/workflow.go, api/services/workflow_test.go, docs/Internal_docs.go, docs/Internal_swagger.yaml, docs/docs.go, docs/swagger.md, docs/swagger.yaml, utils/validator.go, utils/validator_test.go
- Implement /ncns/rebuild API
NOTE: this does not actually create a workflow 
NOTE2: anything under `docs/` `mocks/` are generated code which doesn't need review
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
=> CASMPET-5483

api/argo-templates/base/template.argo.yaml, api/argo-templates/ncn/worker.rebuild.argo.yaml, api/argo-templates/render.go, api/argo-templates/render_test.go, api/services/workflow.go, scripts/argo.local.sh
- remove PoC code in `argo_templates` package
- address comments found from previous PR
- add skeleton template for renderer to work
- update local dev script to use full deployment of argo
**NOTE**: *.argo.yaml files in this PR are just skeleton files for render function to to be tested. The actual workflow definitions will be addressed in https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5465
_List the environments in which …
=> Casmpet 5466 - cleanup PoC code

api/argo-templates/ncn/worker.common.parameters.yaml, api/argo-templates/ncn/worker.drain.yaml, api/argo-templates/ncn/worker.reboot.yaml, api/argo-templates/ncn/worker.rebuild.yaml, api/argo-templates/render.go, go.mod, scripts/argo.local.sh
- add `/root/.ssh` to k3d containers so we can use dry run mode on local
- decouple mono workflow we had into different pieces (no actual work yet)
- introduce useful helm/sprig templating functions like `include` and `indent` so we can better organize workflow template
_How were the changes tested …
=> add more render func

api/argo-templates/ncn/worker.drain.yaml, api/argo-templates/ncn/worker.post-rebuild.yaml, api/argo-templates/ncn/worker.rebuild.yaml, api/argo-templates/ncn/worker.wipe-and-reboot.yaml
copy existing rebuild automation into argo workflow
* Resolves CASMPET-5465
* Change will also be needed in `CASMPET-5465`
- Were continuous …
=> copy existing rebuild automation into argo workflow

api/argo-templates/ncn/worker.drain.yaml, api/argo-templates/ncn/worker.post-rebuild.yaml, scripts/temp.deployment.sh
- CASMPET-5465: replace shell with goss test for pre-drain check
* Resolves CASMPET-5465
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
_Are there known …
=> CASMPET-5465 replace shell with goss test for pre-drain check

api/argo-templates/base/template.argo.yaml, api/argo-templates/ncn/worker.drain.yaml, api/argo-templates/ncn/worker.post-rebuild.yaml, api/argo-templates/ncn/worker.rebuild.yaml, api/argo-templates/ncn/worker.wipe-and-reboot.yaml, api/controllers/v1/ncn.go, scripts/argo.local.sh, scripts/temp.deployment.sh
- fix issues found during nightly testing, there are some syntax issues in the template that i can only test when i have a system
- fix the issue where if you request a rebuild of all workers, it will lock workflow as jobs cannot be put on any workers
- fix the issue where freshly rebuilt workers are not used for rebuilding other workers
* Resolves [CASMPET-5465](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5465)
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
=> Casmpet 5540

api/argo-templates/ncn/common.envar.yaml, api/argo-templates/ncn/worker.wipe-and-reboot.yaml, scripts/temp.deployment.sh
- decouple PoC code into multiple steps
* Resolves [CASMPET-5540](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5540)
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
_Are there known issues with these changes? Any other special considerations?_
=> decouple wipe and reboot script

api/argo-templates/base/template.argo.yaml, api/argo-templates/ncn/worker.rebuild.yaml
- remove mutex so we don't need to deal with locks
- make sure each drain depends on previous drain so we still guarantee one ncn drain at a time
- DAG default is falifast: true, we don't need to have duplicated config
- add pod information so we have more info when debugging
* Resolves [CASMPET-5541](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5541)
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test …
=> Casmpet 5541

README.md, cluster-admin-patch.yaml
Added steps for development setup to the main README.md file
Documentation
N/A
* Virtual …
=> First pass at updating README added two new steps

api/argo-templates/base/kubectlAndCurl.template.argo.yaml, api/argo-templates/base/ssh.template.argo.yaml, api/argo-templates/ncn/worker.drain.yaml, api/argo-templates/ncn/worker.post-rebuild.yaml, api/argo-templates/ncn/worker.rebuild.yaml, api/argo-templates/ncn/worker.wipe-and-reboot.yaml, scripts/temp.deployment.sh
- use curl/kubectl/csi for steps that doesn't require ssh
* Resolves https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5695 and https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5604
* `fanta`
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
_Are there known issues with these changes? Any other special considerations?_
=> change some steps to use curl/kubectl instead of ssh

scripts/argo.local.sh
updated argo.local script to create /usr/bin
_How were the changes tested …
=> Modified argo.local.sh to create /usr/bin

Dockerfile
use distroless
- Were the install/upgrade-based …
=> Casminst 5010: use distroless

.gitignore, charts/v1.0/cray-iuf/Chart.yaml, charts/v1.0/cray-iuf/values.yaml, scripts/argo.local.sh
=> Casmpet 6093 decouple

scripts/temp.deployment.sh
How to use this:
1. copy this script to a system you want to deploy iuf
2. run it 
2.1 `./deploy.sh` will deploy whatever is on master branch
2.2 `./deploy.sh BRANCH_NAME` will deploy the specified branch
* Virtual …
=> q&d deployment for integration test

src/api/argo-templates/base/iufBase.template.argo.yaml, src/api/services/iuf/sessions.go
Edit iuf-base-template, use iuf-container v0.0.2.
I added a volumeMount for ca-certificates. Other workflows/workflowTemplates that reference this template will need to have a volume for ca-certificates.
* `Mug`
* `Frigg`
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …
=> CASMPET-6155 edit iuf-base-template, use iuf-container v0.0.2

.gitignore, charts/v1.0/cray-nls/values.yaml, scripts/argo.local.sh, src/api/services/iuf/activities_test.go, src/api/services/iuf/sessions.go, src/utils/env.go
Find and replace of /etc/iuf to /opt/cray/iuf.
There may be related docs-csm changes.
* …
=> CASM-3678 Move host directory from /etc/iuf to /opt/cray/iuf

charts/v1.0/cray-nls/Chart.yaml, charts/v1.0/cray-nls/values.yaml
=> Casminst 5634

.github/workflows/build_and_release_charts.yaml, .github/workflows/chart_lint_test_scan.yaml
Fix for artifactory authentication.
* Resolves [CASMINST-5735](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5735)
Github Actions workflow completes and authenticates
* Github Actions
Build pipeline
K=Low
=> CASMINST-5735: Update build workflow to authenticate

scripts/temp.deployment.sh
add cray-iuf version to  temp.deployment.sh
- …
=> CASMPET-6212 add cray-iuf version to  temp.deployment.sh

src/api/argo-templates/base/sat-general-template-iuf.argo.yaml
Make improvements to sat-general template as required for usage by `sat bootprep`. This includes:
* Rename the workflow template and the template within.
* Remove the unnecessary (we think) "main" template
* Add input parameters for media_dir and stdout_file_path
* Add output parameter to return the contents of stdout_file_path
* Encapsulate setup code in a function with `set -e` and `set +x` bookends.
* Use a more unique delimiter for the bash here doc, so it is less likely to conflict with calling templates' script_content.
* Add a volume mount for the new media_dir input parameter.
* Remove unnecessary `chmod +x` given that we are executing the script with `bash`.
* Remove global `set -e` so script_content can handle non-zero exit codes as they wish.
Test Description:
Not tested yet. …
=> CASMINST-5693: Improve sat-general template as required by bootprep

README.md, scripts/argo.local.sh
=> fix dev setup: allowing user to specify artifactory credentials

src/api/models/iuf/manifestDataValidation/manifest_data_validate.go, src/api/models/iuf/manifest_validate.go, tests/data/iuf-product-manifest.yaml, tests/manifest_validate_test.go
Modified code to pick the nexus-repositories.yaml file path based on the file path of iuf-product-manifest.yaml which is passed as argument to iuf-validate exe
_How were the changes tested and success …
=> Abs file path

src/api/services/iuf/sessions_workflow_gen.go
Adding "-" to exitHandler name
=> adding - to exit handler name

docs/IUF_docs.go, docs/IUF_swagger.yaml, src/api/models/iuf/shared.go, src/api/services/iuf/activities.go, src/api/services/iuf/sessions_workflow_gen.go, src/api/services/iuf/sessions_workflow_gen_test.go
CASM-4572 Add argo workflows for the Rolling Reboot of worker nodes,storage nodes
* Resolves [CASM-4572](https://jira-pro.it.hpe.com:8443/browse/CASM-4572)
* docs-csm PR: https://github.com/Cray-HPE/docs-csm/pull/6014
* iuf-cli PR : https://github.com/Cray-HPE/iuf-cli/pull/194
* Starlord
=> CASM-4572Add argo workflows for the Rolling Reboot of worker nodes,storage nodes
